## Numpy

NumPy(Numerical Python) 是 Python 語言的一個擴展程式庫，支持大量的維度數組與矩陣運算，此外也針對數組運算提供大量的數學函數庫。

NumPy 的前身 Numeric 最早是由 Jim Hugunin 與其它協作者共同開發，2005 年，Travis Oliphant 在 Numeric 中結合了另一個同性質的程式庫 Numarray 的特色，並加入了其他擴展而開發了 NumPy。NumPy 為開放源代碼並且由許多協作者共同維護開發。

**NumPy 是一個運行速度非常快的數學庫，主要用於數組計算，包含：**

(1) 一個強大的N維數組對象 ndarray

(2) 廣播功能函數

(3) 整合 C/C++/Fortran 代碼的工具

(4) 線性代數、傅裏葉變換、亂數生成等功能

NumPy 官網 http://www.numpy.org/

NumPy 源代碼：https://github.com/numpy/numpy

SciPy 官網：https://www.scipy.org/

SciPy 源代碼：https://github.com/scipy/scipy

**install numpy:**

（1）pip install numpy

（2）conda install -c anaconda numpy


In [2]:
import numpy as np
## import numpy

In [6]:
a = np.array([1,2,3])  
print (a)

[1 2 3]
[1 2 3]


In [15]:
b=[[1,2],[3,4]]
c = np.array([[1,  2],  [3,  4]])


In [ ]:
print(b.)
print(c.)

In [17]:
print(b*2)
print(c*2)

array([[2, 4],
       [6, 8]])